#!/bin/bash

# Script written by Bielecki - https://github.com/Bielecki - please respect my work and don't remove this line.

scriptlocation=$(dirname "${BASH_SOURCE[0]}")
dateofsearch=$(date +%Y-%m-%d)
timeofsearch=$(date +%H-%M-%S)
if [ -n "$1" ]; then
	while true; do
		if [ ! -d "$scriptlocation/customresults" ]; then
			mkdir "$scriptlocation/customresults"
		fi
		if [ ! -f "$scriptlocation/customresults/$dateofsearch $timeofsearch - $1" ]; then
			touch "$scriptlocation/customresults/$dateofsearch $timeofsearch - $1"
		fi
		cache=($(curl http://pastebin.com/api_scraping.php -s | grep '"key":' | awk '{print $2}' | sed -e 's/,$//' -e 's/"//g'))
		for i in "${cache[@]}"; do
			duplicate=$(grep "http://pastebin.com/raw/$i" "$scriptlocation/customresults/$dateofsearch $timeofsearch - $1")
			if [ -z "$duplicate" ]; then
				readpaste=$(curl http://pastebin.com/api_scrape_item.php?i="$i" -s | grep "$1") # you may want to change "grep" here into "egrep" to use regex
				if [ -n "$readpaste" ]; then
					printf "################################\n--------------------------------\nhttp://pastebin.com/raw/$i\n--------------------------------\n\n\n%s\n\n\n" "$readpaste" >> "$scriptlocation/customresults/$dateofsearch $timeofsearch - $1"
				fi
			fi
		done
	sleep 60
	done
else
	printf "Specify word that you want to search in pastes\n"
fi

